name: mwidgets
description:
  Contains a custom widgets like MText, MDropdown, MFileImage, MNetworkImage, MLottie, MSvg,
  MBouncingButton others
version: 1.3.2
homepage: https://github.com/ibrahimnashat/mwidgets.git

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  eitherx: ^2.0.1
  lottie: ^3.3.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  localization: ^2.1.1
  bouncing_widget: ^2.0.0
  pinput: ^5.0.1
  flutter_rating_bar: ^4.0.1
  easy_image_viewer: ^1.5.1
  flash: ^3.1.1
  square_percent_indicater: ^0.1.0
  cupertino_range_slider_improved: ^2.0.1
  phone_numbers_parser: ^9.0.16
  image_zoom_on_move: ^1.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/
