name: mwidgets
description: Contains a custom widgets like MText, MDropdown, MFileImage, MNetworkImage, MLottie, MSvg,
  MBouncingButton others
version: 1.0.3
homepage: https://github.com/ibrahimnashat/mwidgets.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  eitherx: ^1.0.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  localization: ^2.1.1
  bouncing_widget: ^2.0.0
  pinput: ^3.0.1
  flutter_rating_bar: ^4.0.1
  lottie: ^2.7.0
  easy_image_viewer: ^1.2.1
  flash: ^3.1.0
  square_percent_indicater: ^0.1.0
  skeletons: ^0.0.3
  cupertino_range_slider_improved: ^2.0.1
  phone_number: ^2.0.1
  image_zoom_on_move: ^1.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/
